### ISSUE TITLE
Hebrew text direction

### ISSUE THREAD

**Issue by mikesname** [mikesname/docview#400]
When a text box has mixed-script contents (i.e. Hebrew and Latin) what direction does the text get rendered?

**Comment by ygherman** [comment]
http://portal.aehri.dans.knaw.nl/admin/units/il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29#desc-il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29-heb

Still the right alignment of hebrew text issue. but i looked at it from in the admin staging. does that not work still?
Linda has imported all the YV descriptions, which means that now this is reoccurring in all hebrew descriptions. please take a look.

**Comment by mikesname** [comment]
Is it aligned to your satisfaction on the portal:

http://portal.aehri.dans.knaw.nl/units/il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29#desc-il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29-heb

This stuff's really hard though so it probably won't ever be perfect.

**Comment by ygherman** [comment]
Sorry to be annoying ☺ is there a possibility to also align the title?

**Comment by mikesname** [comment]
Added more auto-alignment in 928580d79eeaf1efda66c2d93072bc35c52ebc48.

As we've discussed previously it will be imperfect with "mixed" script content, with the alignment mainly being guessed from the first few characters. This is a browser thing and there's not much I can do about it that won't cause other problems, like misaligning Latin text in other fields.
