### ISSUE TITLE
Guides: free text pages: non-latin characters not saved

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#515]
In free text pages in the research guides non-latin1 characters aren't kept on saving the page, they appear as question marks.

See here (at the bottom in the bibliography):

https://portal.ehri-project.eu/guides/terezin/prisoner_databases

**Comment by mikesname** [comment]
@michalfrankl you're correct, I suspect it's an issue with the MySQL table charset/collation. Will have a look.

**Comment by mikesname** [comment]
@michalfrankl I've hopefully fixed this, test [here](https://portal.ehri-project.eu/guides/terezin/unicode-test).

I've converted the content in the existing tables (after making a backup.) This is somewhat error prone so let me know if you see any more weirdness.

Example MySQL connection params updated in 908db76c225f90110e00e2f68e737a5eaeaab3e4.

**Comment by michalfrankl** [comment]
Thanks, it looks good now.

Michal
