### ISSUE TITLE
Various country reports enhancements 

### ISSUE THREAD

**Issue by retosp** [mikesname/docview#518]
- The Country report should have a TOC (History, Archival Situation, EHRI Data (summary), EHRI Data (extensive).

- The labels for EHRI Data (summary)/(extensive) should be changed to EHRI Research (summary)/(data)

- We have to provide a link to the intro to the country reports (at http://www.ehri-project.eu/national-reports ) from somewhere.

**Comment by mikesname** [comment]
Added floating TOC in 675691a3bc864c7cd323002951ce1c94c49c1187.

**Comment by mikesname** [comment]
Added ugly link to country reports into in 4dd107a9716b74c02b72fcaf1b7f33bcc7f34f8a.
