### ISSUE TITLE
Guides: updating guide doesn't work

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#526]
I'm trying to change information about the second research guide here:

https://portal.ehri-project.eu/admin/guides/jewishcouncil/edit

Beforehand, I have changed the name and path and saved. Now, I can't save the page and I get the message that Path must be unique (which it is). It looks like saving the guide main page without changing path doesn't work.

**Comment by mikesname** [comment]
Ugh, how embarrassing. Could you try it now please.

It will error if you try to create a page with the same path an existing one. I'll try and fix that problem later but I'm a bit busy elsewhere today.

**Comment by michalfrankl** [comment]
Thanks, works now (tested on production).

There is actually one smaller problem there as well which isn't a blocker but is annoying: the Default page is always displayed with the first item from the list, no matter what was selected and saved previously. Therefore, it's rather easy to unknowingly overwrite the default page setting when changing something else in the guide.
