### ISSUE TITLE
Guides: add archival description to one of the guides

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#529]
As discussed at various PMBs, we would also like to include in the guides collection descriptions (or possibly file/item descriptions) that were brought into the database via WP15/19. Currently, there is no GUI to add an archival description to a virtual collection/guide. Linda mentioned that there might be some kind of a rough interface to do this and referred me to you... In whatever way, we need to be able to do this. Thanks!

**Comment by michalfrankl** [comment]
Mike, could you please at least comment on this?

**Comment by mikesname** [comment]
There is currently no way of doing this I'm afraid. I was under the impression that all the actual collection data for the guides would be imported by WP19, as per the data [here](http://portal.aehri.dans.knaw.nl/virtual/wp2-ehri-terezin-research-guide) (some 19,000 items.)  What do you need to add to what?

**Comment by michalfrankl** [comment]
Unfortunatelly, we would like to add collections brought in by WP15/19 which weren't immediatelly added to one of the virtual collections. The reason is that while we have brought the most important data via WP2/19, we should take advantage of the other data that comes into database. We have discussed this several times in the PMB (as something to be done at the end of EHRI).

The problem is that there is no UI for it or that there is no way, if we for instance get you identifiers of relevant collections?

**Comment by mikesname** [comment]
I've jerry rigged the [Create Item Reference](http://portal.aehri.dans.knaw.nl/admin/virtual/wp2-ehri-terezin-research-guide/createRef) / [Remove Item Reference](http://portal.aehri.dans.knaw.nl/admin/virtual/wp2-ehri-terezin-research-guide/deleteRef) functions on staging but it's not pretty. Please test.

**Comment by michalfrankl** [comment]
Thanks! It's a bit rough but hopefully it could be ok for the time being. I'm only concerned that it might be difficult to add collections with very common names. Could the look-up also include identifiers?

Also, when saving, I'm getting a "Permission denied" message. Is it a bug or due to the fact that I don't have write permissions for the collection I'm trying to add?

**Comment by mikesname** [comment]
Could you try again please, I've just added WP2 update/create permissions for that VC. There might still be some kinks to work out after that.

The lookup includes the global identifier at `/units/{id}` - is that not enough?

**Comment by michalfrankl** [comment]
Still the same problem.

The lookup doesn't work on the id as you describe it (I have tested both copying it as a whole, or just a part of it).

**Comment by mikesname** [comment]
For some reason you're not a member of the WP2 group (only WP15). I've fixed that now. Could you please try it again and if it still doesn't work, send me a screen grab of what you see at [the item admin page](http://portal.aehri.dans.knaw.nl/admin/virtual/wp2-ehri-terezin-research-guide).

The select box on the create ref page just accepts a global item ID so pasting one into the box should work, but I'll check it out.

**Comment by michalfrankl** [comment]
Thanks, I can now add an item to the virtual collection.

Re IDs: pasting for instance us-005578-irn60927 doesn't work. Do I misunderstand something?

**Comment by mikesname** [comment]
No, it's broken. I think just a plain text box for the ID and no autocomplete nonsense might be better.

**Comment by michalfrankl** [comment]
Yes, that would be better for us now. But we'll happily live with anything which will do the job.

**Comment by mikesname** [comment]
Okay, removed autocomplete. You can now separate multiple item IDs by commas and it'll add them all at once (or at least it should anyway.)

**Comment by michalfrankl** [comment]
Could you please push the feature to production? Thanks.

**Comment by mikesname** [comment]
@michalfrankl it should already be there. The necessary permissions might not be though...

**Comment by mikesname** [comment]
@michalfrankl I've added permissions for WP2 to update the Terezin guide and create child VCs. Please try it now. This wasn't possible before since the guide did not exist.
