### ISSUE TITLE
Guides: free-text pages in markdown

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#531]
Is it possible to re-enable the creation of markdown free text pages (while also keeping the option to create them in full HTML, with JS)? This was the original idea and the GUI still states that this is possible, but Thibault at one moment removed this functionality. While we need to create some bit more complicated pages, for others, we would profit from a simpler way of coding them. I also think that it's better sustainable and will save us time in the future as we will be revising the architecture of the guides.

**Comment by mikesname** [comment]
Okay done, existing pages are now HTML, new ones can be added with MD.

**Comment by michalfrankl** [comment]
Thanks, very helpful.
