### ISSUE TITLE
Remove "Historical Agents" from Item Type facet (global search)

### ISSUE THREAD

**Issue by retosp** [mikesname/docview#542]
After performing a global search, it is possilbe to filter by Item Type. The list of item types includes "Historical Agents". As we don't do much with authority files/historical agents this should be removed.

In addition, the tooltip when hovering over the Item Type facet should be corrected: remove reference to "authority files", but mention "countries" instead.

**Comment by mikesname** [comment]
Fixed in 2528b2b87952c785489c931f0f55591eb313b64d.
