### ISSUE TITLE
replicated identifier in the URL of the unit of description for YV description

### ISSUE THREAD

**Issue by ygherman** [mikesname/docview#545]
best example see [here](http://portal.aehri.dans.knaw.nl/admin/units/il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29#desc-il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29-heb): 
http://portal.aehri.dans.knaw.nl/admin/units/il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29#desc-il-002798-o-64-o-64-2-o-64-2-sch-o-64-2-sch-2-o-64-2-sch-2-29-heb

this should be like this: http://portal.aehri.dans.knaw.nl/admin/units/il-002798-o-64-2-sch-2-29-heb

**Comment by mikesname** [comment]
This is an issue with the [backend](https://github.com/EHRI/ehri-rest) (for which there is currently an open PR.)
