### ISSUE TITLE
Guides: markdown in "Secondary content"

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#546]
Would it be possible to use markdown in the "Secondary content" of the guides pages as well (it should appear on the right hand side, just above the links). 

If possible, for all pages, not only the markdown pages.

**Comment by mikesname** [comment]
Should it go above or below the existing, optional sidebar content on, e.g. the maps page when you have search results?

**Comment by mikesname** [comment]
Mmmn, the secondary content is apparently used for defining page Javascript on HTML and markdown pages, which means it obviously can't be used for markdown as well... I can change that if you don't need Javascript.

**Comment by mikesname** [comment]
Or, while we're building the world's worst CMS, you could write Javascript to add the markdown you want to the page.

**Comment by michalfrankl** [comment]
Hm, we do use JS on at least one page. If I understand properly, we can
simply add the <script> tag into the markdown, right?

As you imply, the CMS will have to be conceptually redone later on.

**Comment by mikesname** [comment]
Okay I added that. Please update your pages to add <script> tags around your JS.
