### ISSUE TITLE
Guides: already applied conditions in facetted browse not shown

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#554]
In the browse interface for the guides (as it currently funtions on staging), the user doesn't see the already applied conditions, making it difficult to understand the result and the narrowed down content of the facets.

**Comment by mikesname** [comment]
Sorry, a fix for the portal broke the guides. Deploying a fix now. As is often the case I've had to change some related things (e.g. renaming the `kw[]` parameter) so please watch out for collateral damage.

**Comment by michalfrankl** [comment]
Thanks, we will change it. But please don't rename the parameter in the
future, since we link to the facets from the textual guides.

Michal
