### ISSUE TITLE
Guides: child items not displayed

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#561]
Please see for instance here:

https://portal.ehri-project.eu/guides/terezin/browse?q=pachter+vilemina&kw=terezin-terms-keyword-jmp-158

Clicking on the link ("10 child items") only displays the parent unit of description, but no child items. It should work the same way as in the portal interface.

**Comment by mikesname** [comment]
For the time being I'm just going to remove the link. I want to avoid duplicating more of the portal interface in the guides.

**Comment by michalfrankl** [comment]
That's a problem, especially with the data of Beit Theresienstadt where the
authorities are linked to the files and not to the lowest level of
description. It means that the user doesn't really understand why a
particular file was found and will miss the more detailed document level
descriptions. And it's a pro lem elsewhere too.

I know that duplication isn't nice, but if at all possible I'd like to have
that feature in the guides. Indeed, we will rethink it under EHRI-2.

**Comment by mikesname** [comment]
ok done

**Comment by michalfrankl** [comment]
Wonderful, thanks!
