### ISSUE TITLE
Page jumps up while scrolling down

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#563]
In Firefox, open this page:

https://portal.ehri-project.eu/units/cz-002279-collection-jmp-shoah-t-collection-jmp-shoah-t-2-collection-jmp-shoah-t-2-a-collection-jmp-shoah-t-2-a-4-collection-jmp-shoah-t-2-a-4d-collection-jmp-shoah-t-2-a-4d-185

Scroll down; as the the "Archival context" section gets to the top of the window, the page "jumps" back up. I haven't seen such behaviour elsewhere.

There also is huge empty space above the "Search child items..." field.

**Comment by mikesname** [comment]
Attempted a fix for the jumping, let me know if you still see it.

Not much I can do about the white space, other than get rid of the facetting for child items (which can be useful when there are more of them), or rethink the layout completely. In this case the sidebar "context" is much bigger than the item's content. Suggestions on a postcard.

**Comment by michalfrankl** [comment]
Thanks, jumping is gone and the rest is non-critical.
