### ISSUE TITLE
Guides: map: hard-coded default position

### ISSUE THREAD

**Issue by michalfrankl** [mikesname/docview#569]
Apparently, the map pages in the guides have hard-coded default position. That's why even for the position set for Vienna, the map shows Terezín:

https://portal.ehri-project.eu/guides/jewishcouncil/geography

This is urgent, we can't go public with the guide without at least basic functionality of the map.

If that would be no big work, could the initial scale be also configurable?

**Comment by mikesname** [comment]
I can't check right now, but don't you set this in the "default parameters" box on the guide page?

**Comment by mikesname** [comment]
Okay, so that was, um, broken it turns out. Should be fixed now in 5784185b52910382b6c895310c727088a9b0f9d3. You can set the initial scale with "&zoom=10" or whatever.
